import type { Country } from "@shared/schema";

export const serviceCountries: Omit<Country, 'id'>[] = [
  // Türkiye (Kaynak ülke)
  {
    name: "Türkiye",
    code: "TR",
    flag: "🇹🇷",
    image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Kaynak ülke - Türk vatandaşları için vize danışmanlığı hizmetleri",
    processingTime: "Kaynak ülke",
    fee: "Kaynak ülke",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  
  // Ücretsiz Giriş (Vizesiz Seyahat)
  {
    name: "Arjantin",
    code: "AR",
    flag: "🇦🇷",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Arjantin seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Azerbaycan",
    code: "AZ",
    flag: "🇦🇿",
    image: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Azerbaycan seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Bahamalar",
    code: "BS",
    flag: "🇧🇸",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Bahamalar seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Belarus",
    code: "BY",
    flag: "🇧🇾",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Belarus seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 30 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Bosna Hersek",
    code: "BA",
    flag: "🇧🇦",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Bosna Hersek seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün (her 180 günde)",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Brezilya",
    code: "BR",
    flag: "🇧🇷",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Brezilya seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Fas",
    code: "MA",
    flag: "🇲🇦",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Fas seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Filipinler",
    code: "PH",
    flag: "🇵🇭",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Filipinler seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 30 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Güney Kore",
    code: "KR",
    flag: "🇰🇷",
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Güney Kore seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Japonya",
    code: "JP",
    flag: "🇯🇵",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Japonya seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Katar",
    code: "QA",
    flag: "🇶🇦",
    image: "https://images.unsplash.com/photo-1539650116574-75c0c6d68e5d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Katar seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Malezya",
    code: "MY",
    flag: "🇲🇾",
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Malezya seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Sırbistan",
    code: "RS",
    flag: "🇷🇸",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Sırbistan seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Tayland",
    code: "TH",
    flag: "🇹🇭",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Tayland seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 30 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Ukrayna",
    code: "UA",
    flag: "🇺🇦",
    image: "https://images.unsplash.com/photo-1520637836862-4d197d17c90a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Ücretsiz giriş - Türk pasaportunuz varsa Ukrayna seyahat etmek için vizeye ihtiyacınız yoktur",
    processingTime: "Vizesiz - 90 gün kalmak",
    fee: "Vize ücreti yok",
    visaRequired: false,
    eVisaAvailable: false,
    visaOnArrival: false,
  },

  // E-Vize (Online Vize Başvurusu)
  {
    name: "Bahreyn",
    code: "BH",
    flag: "🇧🇭",
    image: "https://images.unsplash.com/photo-1539650116574-75c0c6d68e5d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "E-Vize mevcut - Online başvuru ile Bahreyn vizesi alabilirsiniz",
    processingTime: "e-Vize - 3-5 iş günü",
    fee: "4000₺",
    visaRequired: true,
    eVisaAvailable: true,
    visaOnArrival: false,
  },
  {
    name: "Birleşik Arap Emirlikleri",
    code: "AE",
    flag: "🇦🇪",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "E-Vize mevcut - Online başvuru ile BAE vizesi alabilirsiniz",
    processingTime: "e-Vize - 3-5 iş günü",
    fee: "4000₺",
    visaRequired: true,
    eVisaAvailable: true,
    visaOnArrival: false,
  },
  {
    name: "Hindistan",
    code: "IN",
    flag: "🇮🇳",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "E-Vize mevcut - Online başvuru ile Hindistan vizesi alabilirsiniz",
    processingTime: "e-Vize - 3-5 iş günü",
    fee: "4000₺",
    visaRequired: true,
    eVisaAvailable: true,
    visaOnArrival: false,
  },
  {
    name: "Özbekistan",
    code: "UZ",
    flag: "🇺🇿",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "E-Vize mevcut - Online başvuru ile Özbekistan vizesi alabilirsiniz",
    processingTime: "e-Vize - 3-5 iş günü",
    fee: "4000₺",
    visaRequired: true,
    eVisaAvailable: true,
    visaOnArrival: false,
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "🇱🇰",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "E-Vize mevcut - Online başvuru ile Sri Lanka vizesi alabilirsiniz",
    processingTime: "e-Vize - 3-5 iş günü",
    fee: "4000₺",
    visaRequired: true,
    eVisaAvailable: true,
    visaOnArrival: false,
  },
  {
    name: "Kenya",
    code: "KE",
    flag: "🇰🇪",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "E-Vize mevcut - Online başvuru ile Kenya vizesi alabilirsiniz",
    processingTime: "e-Vize - 5-7 iş günü",
    fee: "4000₺",
    visaRequired: true,
    eVisaAvailable: true,
    visaOnArrival: false,
  },

  // Vize Gerekli
  {
    name: "Almanya",
    code: "DE",
    flag: "🇩🇪",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Almanya konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Polonya",
    code: "PL",
    flag: "🇵🇱",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Polonya konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Bulgaristan",
    code: "BG",
    flag: "🇧🇬",
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Bulgaristan konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Avusturya",
    code: "AT",
    flag: "🇦🇹",
    image: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Avusturya konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Belçika",
    code: "BE",
    flag: "🇧🇪",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Belçika konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Fransa",
    code: "FR",
    flag: "🇫🇷",
    image: "https://images.unsplash.com/photo-1549144511-f099e773c147?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Fransa konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Hollanda",
    code: "NL",
    flag: "🇳🇱",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - Hollanda konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "İtalya",
    code: "IT",
    flag: "🇮🇹",
    image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Schengen vize randevusu gerekli - İtalya konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Birleşik Krallık",
    code: "GB",
    flag: "🇬🇧",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Vize randevusu gerekli - Birleşik Krallık konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Amerika Birleşik Devletleri",
    code: "US",
    flag: "🇺🇸",
    image: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Vize randevusu gerekli - ABD konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 30-60 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
  {
    name: "Kanada",
    code: "CA",
    flag: "🇨🇦",
    image: "https://images.unsplash.com/photo-1503614472-8c93d56cd96b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
    description: "Vize randevusu gerekli - Kanada konsolosluğundan vize randevusu alınması gerekmektedir",
    processingTime: "Vize randevusu - 15-30 gün",
    fee: "8000₺",
    visaRequired: true,
    eVisaAvailable: false,
    visaOnArrival: false,
  },
];